### ISSUE TITLE
Exclude bundles from osgiRuntime

### ISSUE THREAD

**Issue by thugcee** [renatoathaydes/osgi-run#23]
Hi
Is it possible to instruct _osgi-run_ to not install some bundles in started OSGi container? I have a big dependency tree with some packages nor needed actually, but calculated as necessary.

**Comment by renatoathaydes** [comment]
Hi!

Have you tried excluding the dependencies in the gradle file?

Something like this:

```groovy
dependencies {
    osgiRuntime "my-bundle:with-transitive-dependencies:1.0", {
        exclude group: 'bundl-group-to-be-excluded'
    }
}
```

I've never tried this , but I expect this to work because `osgi-run` uses Gradle's configurations to figure out dependencies and install bundles in the OSGi runtime.

If it doesn't work, I think it can be considered a bug.

**Comment by thugcee** [comment]
That didn't work in my case (_osgiRuntime_ was correct and _runtime_ contained unwanted dependencies), but you pointed me in right direction and I've found the solution, thank you :)

My solution was to add:
```[groovy]
configurations {
    ...
    runtime.exclude group: 'org.apache.poi' // unwanted dep.
    runtime.exclude group: 'org.mockito'  // unwanted dep.
}
```

**Comment by renatoathaydes** [comment]
@thugcee cool!
